
CREATE TABLE tbl_member(
M_ID	VARCHAR2(20)	NOT NULL	PRIMARY KEY,
M_PASSWORD	nVARCHAR2(125)	NOT NULL	,
M_LOGIN_DATE	nVARCHAR2(10)		,
M_REM	nVARCHAR2(125)		
);


CREATE TABLE tbl_read_book(
RB_SEQ	NUMBER	NOT NULL	PRIMARY KEY,
RB_BCODE	VARCHAR2(20)	NOT NULL	,
RB_DATE	VARCHAR2(10)	NOT NULL	,
RB_STIME	VARCHAR2(10)		,
RB_RTIME	NUMBER(10,3)		,
RB_SUBJECT	nVARCHAR2(20)		,
RB_TEXT	nVARCHAR2(400)		,
RB_STAR	NUMBER,		
RB_NAME nVARCHAR2(10),
CONSTRAINT FK_READ_BOOK FOREIGN KEY (RB_BCODE)
REFERENCES TBL_BOOKS(B_CODE) ON DELETE CASCADE 
);


CREATE TABLE tbl_books(
B_CODE	VARCHAR2(20),
B_NAME	nVARCHAR2(125)	NOT NULL	,
B_AUTHER	nVARCHAR2(125)	NOT NULL,	
B_COMP	nVARCHAR2(125)		,
B_YEAR	VARCHAR2(10)		,
B_IPRICE	NUMBER	,
CONSTRAINT PK_BOOK PRIMARY KEY (b_code)
);

CREATE SEQUENCE RB_SEQ
START WITH 1 INCREMENT BY 1;


/* system sql */
CREATE TABLESPACE book_db
DATAFILE 'book_db.dbf'
SIZE 10M AUTOEXTEND ON NEXT 10K; 

DROP tablespace info_data;

CREATE USER bookuser IDENTIFIED BY bookuser;

GRANT DBA TO bookuser;
